# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7

cache:
  - pip
  
before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements/tox.txt

script:
  - tox
